import { createDefaultResumeTemplateConfig } from "../templateDefaults.js";

export const LOCAL_RESUME_TEMPLATE_PRESETS = [
  createDefaultResumeTemplateConfig({
    id: "local-executive-modern",
    source: "local",
    name: "Executive Modern",
    slug: "executive-modern",
    description: "A polished leadership resume with strong executive presence.",
    tier: "free",
    category: "executive",
    collections: ["executive", "corporate"],
    audience: ["executive", "director", "senior leadership"],
    ats_friendly: true,
    is_featured: true,
    sort_order: 10,
    colors: {
      accent: "#123047",
      text: "#111827",
      muted: "#667085",
      border: "#D6DEE8",
    },
    typography: {
      font_family: "Montserrat, sans-serif",
      base_font_size: 13,
      line_height: 1.58,
      heading_style: "underlined",
    },
    layout: {
      page: { margin: "wide", columns: 1, section_spacing: "spacious" },
      header: { style: "centered", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-technology-modern",
    source: "local",
    name: "Technology Modern",
    slug: "technology-modern",
    description: "A clean technical template for software, cloud, data, and product roles.",
    tier: "free",
    category: "technology",
    collections: ["technology", "ai_recommended"],
    audience: ["software engineer", "developer", "data", "cloud", "product"],
    ats_friendly: true,
    is_featured: true,
    sort_order: 20,
    colors: {
      accent: "#2563EB",
      text: "#0F172A",
      muted: "#475569",
      border: "#DBEAFE",
    },
    typography: {
      font_family: "Inter, sans-serif",
      base_font_size: 13,
      line_height: 1.6,
      heading_style: "accent_bar",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "normal" },
      header: { style: "left", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-healthcare-clean",
    source: "local",
    name: "Healthcare Clean",
    slug: "healthcare-clean",
    description: "A calm, clinical template for healthcare, operations, and healthcare IT.",
    tier: "free",
    category: "healthcare",
    collections: ["healthcare", "corporate"],
    audience: ["healthcare", "clinical", "nursing", "healthcare operations", "healthcare IT"],
    ats_friendly: true,
    sort_order: 30,
    colors: {
      accent: "#0F766E",
      text: "#102A43",
      muted: "#5B7083",
      border: "#CCFBF1",
    },
    typography: {
      font_family: "Lato, sans-serif",
      base_font_size: 13,
      line_height: 1.64,
      heading_style: "minimal",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "normal" },
      header: { style: "centered", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-government-ats",
    source: "local",
    name: "Government ATS",
    slug: "government-ats",
    description: "A conservative ATS-friendly template for government and compliance roles.",
    tier: "free",
    category: "government",
    collections: ["government"],
    audience: ["government", "public sector", "compliance", "federal contractor"],
    ats_friendly: true,
    sort_order: 40,
    colors: {
      accent: "#374151",
      text: "#111827",
      muted: "#4B5563",
      border: "#D1D5DB",
    },
    typography: {
      font_family: "Arial, sans-serif",
      base_font_size: 12,
      line_height: 1.55,
      heading_style: "uppercase",
    },
    layout: {
      page: { margin: "wide", columns: 1, section_spacing: "compact" },
      header: { style: "left", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-student-internship",
    source: "local",
    name: "Student Internship",
    slug: "student-internship",
    description: "An approachable early-career template for internships and entry-level roles.",
    tier: "free",
    category: "student",
    collections: ["student", "technology"],
    audience: ["student", "internship", "entry level", "new graduate"],
    ats_friendly: true,
    sort_order: 50,
    colors: {
      accent: "#7C3AED",
      text: "#1F2937",
      muted: "#6B7280",
      border: "#E9D5FF",
    },
    typography: {
      font_family: "Nunito, sans-serif",
      base_font_size: 13,
      line_height: 1.66,
      heading_style: "accent_bar",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "spacious" },
      header: { style: "bold_banner", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
  }),
];