// Realistic mock "raw hits" as if each provider had actually returned them.
// Deliberately includes near-duplicates across providers (same person found
// via two sources) so the dedup step has something real to demonstrate —
// nothing here is live data; every record is fictional and clearly scoped
// to this mock dataset only.

export const MOCK_RAW_HITS = [
  // --- Oracle Fusion HCM Payroll cluster ---
  {
    provider: "jobvair",
    name: "Denise Okafor",
    headline: "Oracle Fusion HCM Payroll Functional Lead",
    location: "Atlanta, GA",
    current_title: "Payroll Functional Lead",
    current_company: "Meridian Higher Ed Solutions",
    skills: ["Oracle Fusion HCM", "Payroll", "Benefits", "Higher Education", "Fast Formula"],
    experience: [
      { title: "Payroll Functional Lead", company: "Meridian Higher Ed Solutions", start: "2021", end: "Present", description: "Led Oracle Fusion HCM Payroll implementation for a state university system." },
      { title: "Oracle HCM Consultant", company: "Aurora Consulting Group", start: "2016", end: "2021", description: "Configured Payroll and Benefits modules for public-sector clients." },
    ],
    education: [{ degree: "B.S.", field: "Information Systems", institution: "Georgia State University", year: "2013" }],
    certifications: ["Oracle Fusion HCM Payroll Certified Implementation Specialist"],
    public_profiles: [{ type: "resume", url: null }],
    years_experience: 9,
    industries: ["Higher Education", "Public Sector"],
    source_url: null,
  },
  {
    provider: "web_search",
    name: "Denise Okafor",
    headline: "Speaker bio — Oracle HCM Users Conference 2025",
    location: "Atlanta, Georgia",
    current_title: "Payroll Functional Lead",
    current_company: "Meridian Higher Ed Solutions",
    skills: ["Oracle Fusion HCM", "Payroll", "Fast Formula"],
    experience: [],
    education: [],
    certifications: [],
    public_profiles: [{ type: "conference_bio", url: "https://example-conference.org/speakers/denise-okafor" }],
    years_experience: null,
    industries: ["Higher Education"],
    source_url: "https://example-conference.org/speakers/denise-okafor",
  },
  {
    provider: "web_search",
    name: "Marcus Webb",
    headline: "Senior Oracle HCM Cloud Consultant",
    location: "Charlotte, NC",
    current_title: "Senior Oracle HCM Cloud Consultant",
    current_company: "Palmetto Public Sector Advisors",
    skills: ["Oracle Cloud HCM", "Payroll", "OTL"],
    experience: [
      { title: "Senior Oracle HCM Cloud Consultant", company: "Palmetto Public Sector Advisors", start: "2019", end: "Present", description: "Recent Oracle Fusion configuration for county government payroll migration." },
    ],
    education: [],
    certifications: [],
    public_profiles: [{ type: "company_bio", url: "https://palmettopsa.example.com/team/marcus-webb" }],
    years_experience: 11,
    industries: ["Public Sector"],
    source_url: "https://palmettopsa.example.com/team/marcus-webb",
  },
  {
    provider: "social_web",
    name: "Marcus Webb",
    headline: "Oracle HCM Techno-Functional Lead",
    location: "Charlotte, North Carolina",
    current_title: "Oracle HCM Techno-Functional Lead",
    current_company: "Palmetto Public Sector Advisors",
    skills: ["Oracle Cloud HCM", "OTL", "Benefits"],
    experience: [],
    education: [],
    certifications: [],
    public_profiles: [{ type: "professional_association", url: "https://oracle-users-assoc.example.org/members/marcus-webb" }],
    years_experience: null,
    industries: ["Public Sector"],
    source_url: "https://oracle-users-assoc.example.org/members/marcus-webb",
  },
  {
    provider: "jobvair",
    name: "Theo Landry",
    headline: "Oracle Fusion HCM Payroll Lead",
    location: "Richmond, VA",
    current_title: "Oracle HCM Payroll Lead",
    current_company: "Commonwealth Systems Group",
    skills: ["Oracle Fusion HCM", "Payroll", "Absence Management"],
    experience: [
      { title: "Oracle HCM Payroll Lead", company: "Commonwealth Systems Group", start: "2022", end: "Present", description: "Payroll configuration lead for state agency Fusion rollout." },
    ],
    education: [{ degree: "B.B.A.", field: "Accounting", institution: "Virginia Commonwealth University", year: "2011" }],
    certifications: [],
    public_profiles: [{ type: "resume", url: null }],
    years_experience: 8,
    industries: ["Public Sector"],
    source_url: null,
  },

  // --- Accela developer cluster ---
  {
    provider: "github",
    name: "Priya Natarajan",
    headline: "Full-stack developer — civic tech & permitting systems",
    location: "Atlanta, GA",
    current_title: "Senior Software Engineer",
    current_company: "Fulton County IT",
    skills: ["Accela", "JavaScript", "SQL", "Node.js"],
    experience: [
      { title: "Senior Software Engineer", company: "Fulton County IT", start: "2020", end: "Present", description: "Builds and maintains Accela Civic Platform integrations." },
    ],
    education: [],
    certifications: [],
    public_profiles: [{ type: "github", url: "https://github.com/example-priya-n" }],
    years_experience: 7,
    industries: ["Public Sector"],
    source_url: "https://github.com/example-priya-n",
  },
  {
    provider: "web_search",
    name: "Sam Whitfield",
    headline: "Accela Developer",
    location: "Savannah, GA",
    current_title: "Accela Developer",
    current_company: "Coastal Municipal Solutions",
    skills: ["Accela", "SQL", "JavaScript"],
    experience: [
      { title: "Accela Developer", company: "Coastal Municipal Solutions", start: "2021", end: "Present", description: "Custom Accela scripting and SQL reporting for permitting workflows." },
    ],
    education: [],
    certifications: [],
    public_profiles: [{ type: "company_bio", url: "https://coastalmunicipal.example.com/team/sam-whitfield" }],
    years_experience: 5,
    industries: ["Public Sector"],
    source_url: "https://coastalmunicipal.example.com/team/sam-whitfield",
  },

  // --- Nonprofit fundraising cluster ---
  {
    provider: "jobvair",
    name: "Elena Cortez",
    headline: "Director of Major Gifts",
    location: "Phoenix, AZ",
    current_title: "Director of Major Gifts",
    current_company: "Desert Horizon Foundation",
    skills: ["Major Gifts", "Planned Giving", "Donor Relations", "Capital Campaigns"],
    experience: [
      { title: "Director of Major Gifts", company: "Desert Horizon Foundation", start: "2019", end: "Present", description: "Manages a major-gift portfolio exceeding $1.3M annually." },
    ],
    education: [{ degree: "M.A.", field: "Nonprofit Management", institution: "Arizona State University", year: "2015" }],
    certifications: ["CFRE"],
    public_profiles: [{ type: "resume", url: null }],
    years_experience: 10,
    industries: ["Nonprofit"],
    source_url: null,
  },
  {
    provider: "web_search",
    name: "Grace Liu",
    headline: "VP of Development",
    location: "Phoenix, AZ",
    current_title: "VP of Development",
    current_company: "Sonoran Children's Alliance",
    skills: ["Major Gifts", "Capital Campaigns", "Board Relations"],
    experience: [
      { title: "VP of Development", company: "Sonoran Children's Alliance", start: "2018", end: "Present", description: "Oversees a major-gifts program with portfolios averaging $2M+." },
    ],
    education: [],
    certifications: [],
    public_profiles: [{ type: "conference_bio", url: "https://example-fundraising-summit.org/speakers/grace-liu" }],
    years_experience: 13,
    industries: ["Nonprofit"],
    source_url: "https://example-fundraising-summit.org/speakers/grace-liu",
  },

  // --- Cybersecurity cluster ---
  {
    provider: "jobvair",
    name: "Robert Kim",
    headline: "Cybersecurity Engineer",
    location: "Fairfax, VA",
    current_title: "Cybersecurity Engineer",
    current_company: "Ironclad Federal Systems",
    skills: ["Security+", "Federal Contracting", "Network Security", "Incident Response"],
    experience: [
      { title: "Cybersecurity Engineer", company: "Ironclad Federal Systems", start: "2020", end: "Present", description: "Supports federal contracts requiring active security clearance." },
    ],
    education: [{ degree: "B.S.", field: "Cybersecurity", institution: "George Mason University", year: "2017" }],
    certifications: ["CompTIA Security+"],
    public_profiles: [{ type: "resume", url: null }],
    years_experience: 6,
    industries: ["Federal Government"],
    source_url: null,
    security_clearance: "Active Secret",
  },
  {
    provider: "social_web",
    name: "Alicia Ferro",
    headline: "Senior Security Engineer — DoD contracts",
    location: "Arlington, VA",
    current_title: "Senior Security Engineer",
    current_company: "Bastion Defense Technologies",
    skills: ["Security+", "CISSP", "Federal Contracting", "Zero Trust"],
    experience: [
      { title: "Senior Security Engineer", company: "Bastion Defense Technologies", start: "2017", end: "Present", description: "Leads security engineering for DoD-facing systems." },
    ],
    education: [],
    certifications: ["CISSP", "CompTIA Security+"],
    public_profiles: [{ type: "professional_association", url: "https://isc2-members.example.org/alicia-ferro" }],
    years_experience: 12,
    industries: ["Federal Government"],
    source_url: "https://isc2-members.example.org/alicia-ferro",
  },
];
