import {
  ASSISTANT_RESPONSE_VERSION,
  BUILDER_ASSISTANT_PAYLOAD_VERSION,
  createEmptyBuilderAssistantPayload,
} from "./assistantContracts.js";
import {
  validateAssistantResponse,
  validateBuilderAssistantPayload,
} from "./assistantValidation.js";
import { createPatchPreviewDiff } from "./diffHelpers.js";
import { applyPatchPreview as applyResponsePatchPreview } from "./patchHelpers.js";
import { edgeFetch } from "../lib/edgeFetch.js";

const cloneValue = value => {
  if (typeof structuredClone === "function") {
    return structuredClone(value);
  }
  return JSON.parse(JSON.stringify(value));
};

const normalizeArray = value => (Array.isArray(value) ? cloneValue(value) : []);
const normalizeObject = value =>
  value && typeof value === "object" && !Array.isArray(value) ? cloneValue(value) : {};

/**
 * Build the canonical assistant payload from Resume Builder-shaped state.
 *
 * This mapper accepts explicit contract fields first, plus common aliases that
 * future BuilderPage wiring is likely to have available. It does not read from
 * Supabase and does not mutate the incoming state.
 *
 * @param {Object} builderState
 * @returns {import("./assistantContracts.js").BuilderAssistantPayload}
 */
export function buildPayload(builderState = {}) {
  const emptyPayload = createEmptyBuilderAssistantPayload();
  const resume = builderState.resume || builderState.currentResume || {};
  const user = builderState.user || {};

  return {
    ...emptyPayload,
    version: BUILDER_ASSISTANT_PAYLOAD_VERSION,
    resume_id: builderState.resume_id ?? resume.id ?? null,
    user_id: builderState.user_id ?? user.id ?? null,
    resume_name: builderState.resume_name ?? resume.name ?? resume.title ?? "",
    header: normalizeObject(builderState.header ?? builderState.headerConfig),
    sections: normalizeArray(builderState.sections ?? builderState.resumeSections),
    jobs: normalizeArray(builderState.jobs ?? builderState.workExperience),
    template: normalizeObject(builderState.template ?? builderState.selectedTemplate),
    profile_context: normalizeObject(builderState.profile_context ?? builderState.profileContext ?? builderState.profile),
    instruction: typeof builderState.instruction === "string" ? builderState.instruction : "",
    job_description: typeof builderState.job_description === "string" ? builderState.job_description : "",
    action_preset: builderState.action_preset ?? null,
  };
}

/**
 * Validate a canonical builder assistant payload.
 *
 * @param {unknown} payload
 */
export function validatePayload(payload) {
  return validateBuilderAssistantPayload(payload);
}

function createMockAssistantResponse(payload) {
  const summarySection = payload.sections.find(section => section.section_type === "summary");
  const firstJob = payload.jobs[0];
  const hasSummaryText = Boolean(summarySection?.content?.text || summarySection?.content?.body);
  const operations = [];
  const suggestions = [];

  if (summarySection && !hasSummaryText) {
    operations.push({
      op: "merge",
      target: `sections[${payload.sections.indexOf(summarySection)}].content`,
      value: {
        text: "Add a focused professional summary tailored to the target role.",
      },
      metadata: {
        reason: "Summary section is present but appears empty.",
        source: "builder_payload",
        evidence: ["summary section has no text"],
        confidence: 0.72,
        safe_to_apply: false,
      },
    });
  }

  if (firstJob) {
    suggestions.push({
      id: "mock_sug_1",
      type: "missing_metric",
      target: "jobs[0].description",
      message: "Consider adding a measurable outcome to the first work experience entry.",
      severity: "medium",
      confidence: 0.68,
      action: "improve_bullet",
      metadata: {
        reason: "Impact metrics help recruiters evaluate scope and results.",
        source: "builder_payload",
        evidence: [firstJob.job_title || firstJob.company || "first job entry"],
        confidence: 0.68,
        safe_to_apply: false,
      },
    });
  }

  return {
    version: ASSISTANT_RESPONSE_VERSION,
    message: "Mock assistant response generated locally for development.",
    confidence: {
      overall: 0.75,
      rationale: "Development mock based on available builder payload fields only.",
    },
    patch: {
      header: {},
      sections: [],
      jobs: [],
      operations,
    },
    suggestions,
    warnings: [
      {
        code: "mock_response",
        message: "This response is a local mock and was not generated by an AI provider.",
        severity: "low",
      },
    ],
  };
}

/**
 * Request assistant suggestions.
 *
 * Calls the authenticated `builder-assistant` Supabase Edge Function. If the
 * function is unreachable (e.g. not deployed yet in local dev), this falls
 * back to a local mock response so the UI remains usable during development.
 * The fallback always carries a `mock_response` warning so callers can tell
 * the difference.
 *
 * @param {import("./assistantContracts.js").BuilderAssistantPayload} payload
 * @returns {Promise<import("./assistantContracts.js").AssistantResponse>}
 */
export async function requestSuggestions(payload) {
  const payloadValidation = validatePayload(payload);
  if (!payloadValidation.valid) {
    const error = new Error("Invalid builder assistant payload.");
    error.validation = payloadValidation;
    throw error;
  }

  let response;
  try {
    response = await edgeFetch("builder-assistant", payload);
  } catch (err) {
    console.warn("[assistant] builder-assistant Edge Function unavailable, using local mock:", err.message);
    response = createMockAssistantResponse(payload);
  }

  const responseValidation = validateResponse(response);
  if (!responseValidation.valid) {
    const error = new Error("Invalid assistant response.");
    error.validation = responseValidation;
    throw error;
  }

  return response;
}

/**
 * Validate an assistant response.
 *
 * @param {unknown} response
 */
export function validateResponse(response) {
  return validateAssistantResponse(response);
}

/**
 * Apply an assistant response to a cloned payload and return preview metadata.
 *
 * @param {import("./assistantContracts.js").BuilderAssistantPayload} payload
 * @param {import("./assistantContracts.js").AssistantResponse} response
 */
export function applyPatchPreview(payload, response) {
  return {
    ...applyResponsePatchPreview(payload, response),
    diff: createPatchPreviewDiff(payload, response).changes,
  };
}

