import { createDefaultResumeTemplateConfig } from "../templateDefaults.js";

export const LOCAL_RESUME_TEMPLATE_PRESETS = [
  createDefaultResumeTemplateConfig({
    id: "local-executive-modern",
    source: "local",
    name: "Executive Modern",
    slug: "executive-modern",
    description: "A polished leadership resume with strong executive presence.",
    tier: "free",
    category: "executive",
    collections: ["executive", "corporate"],
    audience: ["executive", "director", "senior leadership"],
    ats_friendly: true,
    is_featured: true,
    sort_order: 10,
    colors: {
      accent: "#0B1F33",
      text: "#111827",
      muted: "#667085",
      border: "#B8C4D2",
    },
    typography: {
      font_family: "Montserrat, sans-serif",
      base_font_size: 13,
      line_height: 1.58,
      heading_style: "underlined",
    },
    layout: {
      page: { margin: "wide", columns: 1, section_spacing: "spacious" },
      header: { style: "centered", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
    visual_style: {
      header_treatment: "executive_frame",
      section_heading_treatment: "executive_rule",
      divider_color: "#B8C4D2",
      contact_layout: "stacked",
      name_size_delta: 17,
      name_weight: 800,
      name_letter_spacing: "0.02em",
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-technology-modern",
    source: "local",
    name: "Technology Modern",
    slug: "technology-modern",
    description: "A clean technical template for software, cloud, data, and product roles.",
    tier: "free",
    category: "technology",
    collections: ["technology", "ai_recommended"],
    audience: ["software engineer", "developer", "data", "cloud", "product"],
    ats_friendly: true,
    is_featured: true,
    sort_order: 20,
    colors: {
      accent: "#2563EB",
      text: "#0F172A",
      muted: "#475569",
      border: "#BFDBFE",
    },
    typography: {
      font_family: "Inter, sans-serif",
      base_font_size: 13,
      line_height: 1.6,
      heading_style: "accent_bar",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "normal" },
      header: { style: "left", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
    visual_style: {
      header_treatment: "tech_rule",
      section_heading_treatment: "tech_pill",
      divider_color: "#BFDBFE",
      contact_layout: "inline",
      name_size_delta: 15,
      name_weight: 850,
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-healthcare-clean",
    source: "local",
    name: "Healthcare Clean",
    slug: "healthcare-clean",
    description: "A calm, clinical template for healthcare, operations, and healthcare IT.",
    tier: "free",
    category: "healthcare",
    collections: ["healthcare", "corporate"],
    audience: ["healthcare", "clinical", "nursing", "healthcare operations", "healthcare IT"],
    ats_friendly: true,
    sort_order: 30,
    colors: {
      accent: "#0F766E",
      text: "#102A43",
      muted: "#5B7083",
      border: "#99F6E4",
    },
    typography: {
      font_family: "Lato, sans-serif",
      base_font_size: 13,
      line_height: 1.68,
      heading_style: "minimal",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "spacious" },
      header: { style: "centered", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
    visual_style: {
      header_treatment: "healthcare_calm",
      section_heading_treatment: "healthcare_subtle",
      divider_color: "#99F6E4",
      contact_layout: "stacked",
      name_size_delta: 14,
      name_weight: 700,
      name_letter_spacing: "0",
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-government-ats",
    source: "local",
    name: "Government ATS",
    slug: "government-ats",
    description: "A conservative ATS-friendly template for government and compliance roles.",
    tier: "free",
    category: "government",
    collections: ["government"],
    audience: ["government", "public sector", "compliance", "federal contractor"],
    ats_friendly: true,
    sort_order: 40,
    colors: {
      accent: "#111827",
      text: "#111827",
      muted: "#4B5563",
      border: "#D1D5DB",
    },
    typography: {
      font_family: "Arial, sans-serif",
      base_font_size: 12,
      line_height: 1.52,
      heading_style: "uppercase",
    },
    layout: {
      page: { margin: "wide", columns: 1, section_spacing: "compact" },
      header: { style: "left", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
    visual_style: {
      header_treatment: "government_plain",
      section_heading_treatment: "government_block",
      divider_color: "#111827",
      contact_layout: "inline",
      name_size_delta: 12,
      name_weight: 800,
      name_letter_spacing: "0.01em",
    },
  }),
  createDefaultResumeTemplateConfig({
    id: "local-student-internship",
    source: "local",
    name: "Student Internship",
    slug: "student-internship",
    description: "An approachable early-career template for internships and entry-level roles.",
    tier: "free",
    category: "student",
    collections: ["student", "technology"],
    audience: ["student", "internship", "entry level", "new graduate"],
    ats_friendly: true,
    sort_order: 50,
    colors: {
      accent: "#7C3AED",
      text: "#1F2937",
      muted: "#6B7280",
      border: "#DDD6FE",
    },
    typography: {
      font_family: "Nunito, sans-serif",
      base_font_size: 13,
      line_height: 1.7,
      heading_style: "accent_bar",
    },
    layout: {
      page: { margin: "normal", columns: 1, section_spacing: "spacious" },
      header: { style: "bold_banner", contact_separator: "dot", show_headline: true },
      body: { layout_type: "single_column" },
    },
    visual_style: {
      header_treatment: "student_banner",
      section_heading_treatment: "student_bar",
      divider_color: "#DDD6FE",
      contact_layout: "inline",
      header_background: "#7C3AED",
      header_padding: "22px 26px",
      name_size_delta: 16,
      name_weight: 900,
    },
  }),
];